### ISSUE TITLE
On Windows, trying to run "pydoc" as a program does not work

### ISSUE THREAD

**Issue by jonmoore** [statmobile/pydoc#10]
On Windows, pydoc-browse suffers from non-availability of a "pydoc" executable, as [here](http://stackoverflow.com/q/5762712).  Elsewhere pydoc uses `pydoc-command` instead of "pydoc" and that may be better here too.  

Also, "-b" is not a recognized argument for pydoc in Python 2.

I will try to submit a fix.

Overall, thanks for a very useful project.

**Comment by jkitchin** [comment]
I just pushed a fix for the pydoc command. and the -b is removed.

**Comment by jonmoore** [comment]
Thanks, I have an additional suggested change, so that the browser is still opened the first time the process is created.  I'll submit a pull request.

**Comment by jonmoore** [comment]
Thanks, it's working nicely now.
