### ISSUE TITLE
Unsupported use of pip.get_installed_modules()

### ISSUE THREAD

**Issue by trillioneyes** [statmobile/pydoc#20]
See https://github.com/pypa/pip/issues/5243. `pip.get_installed_modules()` is used in the function `pydoc-user-modules` at `pydoc.el:466`. As detailed in the link, the correct way to access this functionality is to use `pkg_resources` instead of `pip` and then access `pkg_resources.working_set`. If I have time I'll make a pull request soon.

**Comment by jkitchin** [comment]
This only seems to be relevant if your version of pip is less than 10. for 10 or greater, the recommended way of using "pip list" seems to be used.

Can you clarify where pkg_resources is? Is it a python2 thing? I have setuptools installed in my py3 setup, but there is no pkg_resources to import.

**Comment by wifijanitor** [comment]
@jkitchin 
pkg_resources is part of setuptools

as an example:
```
import pkg_resources
for dist in pkg_resources.WorkingSet():
    print(dist.project_name)
```

will show you what you have installed
