### ISSUE TITLE
dash dependency

### ISSUE THREAD

**Issue by patxoca** [statmobile/pydoc#3]
pydoc uses some functionality from dash but does not require it.

**Comment by jkitchin** [comment]
what functionality? I only saw one line using a dash function, and it was commented out. I have deleted that line.

**Comment by patxoca** [comment]
My fault. In the process of switching from a pydoc.el inside my config to a git clone of the package I have forgotten to delete pydoc.elc. Once deleted, emacs loads the correct version. Sorry for the noise.

OTOH, pydoc faces on my current theme look ugly. Would you be interested in a patch to make them customizable?

**Comment by jkitchin** [comment]
We could consider a pull request for that kind of customization.

**Comment by statmobile** [comment]
I agree with @jkitchin, although if I had to request something along those lines I would prefer to see it leverage the [Font Lock](http://www.gnu.org/software/emacs/manual/html_node/emacs/Font-Lock.html) minor mode as opposed to being hard-coded in the pydoc package.

**Comment by patxoca** [comment]
My first idea was using `defface` but I'm open to suggestions. This weekend I'll fork the repo and start playing with this.
